name: The Narwal
favicon: null
layout_spectrum: 0.05278009851463139
typography_spectrum: 0.3423031547572464
title: The Narwal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8701988589018583
  lightness: 0.14092414965853095
  saturation: 0.18090982595458627
  rhythmicContrast: 0.7748891215305775
purpose: []
